TEMPLATE = aux

INSTALLER = obmodels

INPUT = $$PWD/config/config.xml $$PWD/packages
example.input = INPUT
example.output = $$INSTALLER
example.commands = /home/turboss/Qt/Tools/QtInstallerFramework/3.0/bin/binarycreator -c $$PWD/config/config.xml -p $$PWD/packages ${QMAKE_FILE_OUT}
example.CONFIG += target_predeps no_link combine

QMAKE_EXTRA_COMPILERS += example

OTHER_FILES = README

DISTFILES += \
    packages/org.ob.models/meta/package.xml \
    packages/org.ob.backend/meta/installscript.js \
    packages/org.ob.backend/data/Tools/fileFlags/_bz2.pyd \
    packages/org.ob.backend/data/Tools/fileFlags/_hashlib.pyd \
    packages/org.ob.backend/data/Tools/fileFlags/_lzma.pyd \
    packages/org.ob.backend/data/Tools/fileFlags/_socket.pyd \
    packages/org.ob.backend/data/Tools/fileFlags/_ssl.pyd \
    packages/org.ob.backend/data/Tools/fileFlags/pyexpat.pyd \
    packages/org.ob.backend/data/Tools/fileFlags/select.pyd \
    packages/org.ob.backend/data/Tools/fileFlags/unicodedata.pyd \
    packages/org.ob.backend/data/Tools/fileFlags/collections/__init__.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/collections/abc.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/email/__init__.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/email/_encoded_words.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/email/_header_value_parser.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/email/_parseaddr.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/email/_policybase.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/email/base64mime.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/email/charset.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/email/contentmanager.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/email/encoders.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/email/errors.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/email/feedparser.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/email/generator.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/email/header.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/email/headerregistry.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/email/iterators.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/email/message.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/email/parser.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/email/policy.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/email/quoprimime.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/email/utils.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/__init__.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/aliases.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/ascii.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/base64_codec.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/big5.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/big5hkscs.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/bz2_codec.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/charmap.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/cp037.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/cp1006.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/cp1026.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/cp1125.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/cp1140.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/cp1250.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/cp1251.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/cp1252.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/cp1253.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/cp1254.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/cp1255.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/cp1256.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/cp1257.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/cp1258.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/cp273.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/cp424.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/cp437.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/cp500.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/cp65001.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/cp720.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/cp737.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/cp775.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/cp850.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/cp852.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/cp855.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/cp856.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/cp857.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/cp858.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/cp860.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/cp861.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/cp862.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/cp863.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/cp864.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/cp865.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/cp866.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/cp869.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/cp874.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/cp875.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/cp932.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/cp949.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/cp950.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/euc_jis_2004.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/euc_jisx0213.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/euc_jp.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/euc_kr.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/gb18030.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/gb2312.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/gbk.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/hex_codec.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/hp_roman8.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/hz.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/idna.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/iso2022_jp.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/iso2022_jp_1.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/iso2022_jp_2.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/iso2022_jp_2004.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/iso2022_jp_3.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/iso2022_jp_ext.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/iso2022_kr.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/iso8859_1.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/iso8859_10.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/iso8859_11.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/iso8859_13.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/iso8859_14.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/iso8859_15.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/iso8859_16.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/iso8859_2.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/iso8859_3.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/iso8859_4.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/iso8859_5.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/iso8859_6.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/iso8859_7.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/iso8859_8.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/iso8859_9.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/johab.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/koi8_r.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/koi8_t.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/koi8_u.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/kz1048.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/latin_1.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/mac_arabic.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/mac_centeuro.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/mac_croatian.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/mac_cyrillic.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/mac_farsi.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/mac_greek.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/mac_iceland.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/mac_latin2.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/mac_roman.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/mac_romanian.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/mac_turkish.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/mbcs.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/oem.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/palmos.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/ptcp154.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/punycode.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/quopri_codec.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/raw_unicode_escape.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/rot_13.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/shift_jis.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/shift_jis_2004.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/shift_jisx0213.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/tis_620.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/undefined.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/unicode_escape.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/unicode_internal.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/utf_16.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/utf_16_be.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/utf_16_le.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/utf_32.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/utf_32_be.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/utf_32_le.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/utf_7.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/utf_8.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/utf_8_sig.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/uu_codec.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/encodings/zlib_codec.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/html/__init__.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/html/entities.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/http/__init__.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/http/client.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/http/server.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/importlib/__init__.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/importlib/_bootstrap.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/importlib/_bootstrap_external.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/importlib/abc.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/importlib/machinery.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/importlib/util.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/logging/__init__.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/pydoc_data/__init__.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/pydoc_data/topics.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/unittest/__init__.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/unittest/case.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/unittest/loader.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/unittest/main.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/unittest/result.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/unittest/runner.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/unittest/signals.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/unittest/suite.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/unittest/util.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/urllib/__init__.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/urllib/parse.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/xml/parsers/__init__.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/xml/parsers/expat.pyc \
    packages/org.ob.backend/data/Tools/fileFlags/xml/__init__.pyc \
    packages/org.ob.backend/meta/package.xml \
    packages/org.ob.models/meta/package.xml \
    packages/org.ob.backend/data/Tools/fileFlags/python36.zip \
    packages/org.ob.backend/data/Tools/fileFlags/pydoc_data/_pydoc.css \
    packages/org.ob.backend/data/Tools/fileFlags/email/architecture.rst \
    packages/org.ob.backend/data/Tools/findSoundCard.bat \
    packages/org.ob.backend/data/Tools/ff7_install_OVA.reg \
    packages/org.ob.backend/data/Tools/ff7_opengl_OVA.reg \
    packages/org.ob.models/meta/installscript.js

FORMS += \
    packages/org.ob.backend/meta/targetwidget.ui
